systems.comodal.json_iterator=software.sava:json-iterator
software.sava.core=software.sava:sava-core
software.sava.rpc=software.sava:sava-rpc
software.sava.ravina_core=software.sava:ravina-core
software.sava.ravina_solana=software.sava:ravina-solana
io.fusionauth.http=io.fusionauth:java-http
org.postgresql.jdbc=org.postgresql:postgresql
